import pymongo

dao = pymongo.MongoClient()

DB_NAME = "inhouse_stats"
GAME_COLLECTION_NAME = "games" 
GAME_RESULT_COLLECTION_NAME = "game_results" # individual summoner results

ID_KEY_NAME = "_id"

db = dao[DB_NAME]

def insertGame(gameJsonData):
    # set _id to game ID
    gameId = gameJsonData['game']['id']
    gameJsonData[ID_KEY_NAME] = gameId
    
    db[GAME_COLLECTION_NAME].insert(gameJsonData)

def insertGameResult(gameResultJsonData):
    # let _id be autogenerated
    db[GAME_RESULT_COLLECTION_NAME].insert(gameResultJsonData)
    
